---
abstract: 'Perl library for pileup using the Biosamtools package'
author:
  - 'Richard de Borja <richard.deborja@sickkids.ca>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: NGS-Tools-BamUtils
provides:
  NGS::Tools::BamUtils:
    file: lib/NGS/Tools/BamUtils.pm
    version: 0.06
  NGS::Tools::BamUtils::Roles::PileupPostProcess:
    file: lib/NGS/Tools/BamUtils/Roles/PileupPostProcess.pm
    version: 0
  NGS::Tools::BamUtils::Roles::PileupUtilities:
    file: lib/NGS/Tools/BamUtils/Roles/PileupUtilities.pm
    version: 0
requires:
  Bio::DB::Sam: 0
  Moose: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.06
